/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './message-input.component.ngfactory';
import * as import2 from './message-input.component';
import * as import3 from './message.service';
import * as import4 from './message-list.component.ngfactory';
import * as import5 from './message-list.component';
import * as import6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_MessagesComponent,
  data: {}
}
);
export function View_MessagesComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-input',([] as any[]),(null as any),(null as any),(null as any),import1.View_MessageInputComponent_0,import1.RenderType_MessageInputComponent)),
    import0.ɵdid(114688,(null as any),0,import2.MessageInputComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),(null as any),import4.View_MessageListComponent_0,import4.RenderType_MessageListComponent)),
    import0.ɵdid(114688,(null as any),0,import5.MessageListComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    ck(v,4,0);
    ck(v,12,0);
  },(null as any));
}
function View_MessagesComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-messages',([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,RenderType_MessagesComponent)),
    import0.ɵdid(49152,(null as any),0,import6.MessagesComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MessagesComponentNgFactory:import0.ComponentFactory<import6.MessagesComponent> = import0.ɵccf('app-messages',import6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbWpyaGEvRG9jdW1lbnRzL0RvY3VtZW50cy9EZXZlbG9wbWVudC9VZGVteSBBbmd1bGFyIE5vZGUgSlMvc2VlZC1wcm9qZWN0L3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9tanJoYS9Eb2N1bWVudHMvRG9jdW1lbnRzL0RldmVsb3BtZW50L1VkZW15IEFuZ3VsYXIgTm9kZSBKUy9zZWVkLXByb2plY3Qvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvbWpyaGEvRG9jdW1lbnRzL0RvY3VtZW50cy9EZXZlbG9wbWVudC9VZGVteSBBbmd1bGFyIE5vZGUgSlMvc2VlZC1wcm9qZWN0L3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvbWpyaGEvRG9jdW1lbnRzL0RvY3VtZW50cy9EZXZlbG9wbWVudC9VZGVteSBBbmd1bGFyIE5vZGUgSlMvc2VlZC1wcm9qZWN0L3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgIDxhcHAtbWVzc2FnZS1pbnB1dD48L2FwcC1tZXNzYWdlLWlucHV0PlxuICAgIDwvZGl2PlxuICAgIDxocj5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8YXBwLW1lc3NhZ2UtbGlzdD48L2FwcC1tZXNzYWdlLWxpc3Q+XG4gICAgPC9kaXY+XG4gICIsIjxhcHAtbWVzc2FnZXM+PC9hcHAtbWVzc2FnZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDSTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWlCO0lBQ2Y7Z0JBQUE7SUFBdUM7SUFDbkM7SUFDTjtJQUFJO01BQ0o7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFpQjtJQUNmO2dCQUFBO0lBQXFDO0lBQ2pDOzs7SUFMSjtJQUlBOzs7OztJQ05OO2dCQUFBOzs7OyJ9
